dist: trusty
language: node_js
node_js:
  - "8"
jobs:
  include:
    - stage: unit
      script: yarn run unit
      after_success:
        bash <(curl -s https://codecov.io/bash)
    - stage: deploy
      script: yarn run build
      deploy:
        provider: pages
        skip_cleanup: true
        local_dir: dist
        repo: altrass/the-lands-of-altrass
        github_token: $GITHUB_TOKEN
        on:
          branch: master
